# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30

# No labels should be exempt from becoming stale because either
# the issue is actually stale/obsolete and should be closed, or
# the issue is important and the stale notification is a good reminder to take action.
# exemptLabels:

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has not had any recent activity.
  To keep our open issue list representative of our actual priorities,
  it will be closed if no further activity occurs.
  If this issue should stay open, simply remove the stale label.
  Thank you for your contributions.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
