# Number of days of inactivity before an issue becomes stale
daysUntilStale: 150

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30

# No labels should be exempt from becoming stale because either
# the issue is actually stale/obsolete and should be closed, or
# the issue is important and the stale notification is a good reminder to take action.
# exemptLabels:

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Please post an update to this issue or close if it is no longer relevant.

  If this issue receives no more activity it will be closed automatically.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
